services:
  postgres:
    image: postgres:15-alpine
    container_name: minimal-cms-db
    environment:
      POSTGRES_DB: minimal_cms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Lisbon
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: minimal-cms-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: minimal_cms
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 3000
      TZ: Europe/Lisbon
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
